Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000]
"AllowSnapshot"=dword:00000001
"AllowSubscription"=dword:00000001
"AllowRSOverlay"="true"
"AllowSkins"="true"
"AutoColorDepthReduction_NA"=dword:00000001
"DisableVCEPowerGating"=dword:00000000
"EnableUlps"=dword:00000001
"EnableUlps_NA"=dword:00000001
"StutterMode"=dword:0000200a
"PP_GPUPowerDownEnabled"=dword:00000001
"DisableUVDPowerGatingDynamic"=-
"DisablePowerGating"=-
"DisableDrmdmaPowerGating"=-
"DisableDMACopy"=-
"DisableBlockWrite"=-
"LTRSnoopL1Latency"=-
"LTRSnoopL0Latency"=-
"LTRNoSnoopL1Latency"=-
"LTRMaxNoSnoopLatency"=-
"KMD_RpmComputeLatency"=-
"DalUrgentLatencyNs"=-
"memClockSwitchLatency"=-
"PP_RTPMComputeF1Latency"=-
"PP_DGBMMMaxTransitionLatencyUvd"=-
"PP_DGBPMMaxTransitionLatencyGfx"=-
"DalNBLatencyForUnderFlow"=-
"BGM_LTRSnoopL1Latency"=-
"BGM_LTRSnoopL0Latency"=-
"BGM_LTRNoSnoopL1Latency"=-
"BGM_LTRNoSnoopL0Latency"=-
"BGM_LTRMaxSnoopLatencyValue"=-
"BGM_LTRMaxNoSnoopLatencyValue"=-
